{
 "title": "kafka Overview",
 "description": "kafka resource usage and throughput",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Brokers Online",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount)"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount)"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions)"
    }
   ]
  },
  {
   "title": "Under Min ISR Partitions",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underminisrpartitioncount)"
    }
   ]
  },
  {
   "title": "At Min ISR Partitions Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_atminisrpartitioncount)"
    }
   ]
  },
  {
   "title": "Partition Leader Distribution STDDEV",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "stddev(kafka_server_replicamanager_leadercount)"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underminisrpartitioncount)"
    }
   ]
  },
  {
   "title": "Partition Distribution STDDEV",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "stddev(kafka_server_replicamanager_partitioncount)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percentunit", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "count(kafka_server_kafkaserver_brokerstate)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_underreplicatedpartitions",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Under Min ISR Partitions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_underminisrpartitioncount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "At Min ISR Partitions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_atminisrpartitioncount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partitions Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_partitioncount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partitions Leader Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_leadercount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(increase(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic!=\"\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(increase(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic!=\"\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(increase(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic!=\"\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages In Per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(increase(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic=\"\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(increase(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic=\"\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(increase(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic=\"\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}